#!/bin/bash

# Copyright (c) 2019 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

[[ -e CMD_LOG ]] || touch CMD_LOG
echo ""
echo "this is a blast from bash" >> CMD_LOG
echo ""
echo ""