#!/bin/bash

# Copyright (c) 2019 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

echo ""
echo ""
echo "this is bash simple connector"
echo ""
echo "tx: $1"
echo ""
echo "pwd: $2"
echo ""
PWD=$2
cd $PWD
FINAL_HOST=$(grep -v 'localhost' <<< $HOST && echo "localhost" || echo "not localhost")
if [[ 1 ]]
then
LOG=$(cat "$PWD"/screenlog.0 | grep {)
while [[ -z $LOG ]]
do
LOG=$(cat "$PWD"/screenlog.0 | grep {)
done
echo $LOG > "$PWD"/response.json
sed -i.backup 's+!+ +g' "$PWD"/response.json
LOG=$(cat "$PWD"/response.json)
CMD=$(echo $LOG | cut -c 11-)
FINAL_CMD=$(echo $CMD | tr -d '"}\r')
$FINAL_CMD &
fi ## if [[ $FINAL_HOST == "localhost" ]]
touch cmd_complete